### ISSUE TITLE
Layout?

### ISSUE THREAD

**Issue by nickwild-999** [rakarmp/astro-shadcn-ui#2]
This is a great time saver thanks. 

Is there any reason you have chosen to not include a `MainLayout.astro` file?

**Comment by rakarmp** [comment]
Thank you for your question! The reason I did not include a MainLayout.astro file in this starter template is to provide flexibility to the users. By not including MainLayout.astro by default, users can easily customize the layout and structure of the pages according to their needs.
However, if you would like to use MainLayout.astro in your project, you can easily create it yourself or add it to this starter template. MainLayout.astro can be used to create a common layout that will be used across your website pages.
I hope this explanation helps! If you have any further questions, feel free to ask.

**Comment by rakarmp** [comment]
> This is a great time saver thanks.
> 
> Is there any reason you have chosen to not include a `MainLayout.astro` file?

I apologize for the delayed response. I'm sorry that it took me this long to address your question. Due to unforeseen circumstances, I was unable to attend to the issue promptly. I understand that your time is valuable, and I sincerely apologize for any inconvenience caused.
Please let me know if there's anything else I can assist you with. Thank you for your understanding.

**Comment by nickwild-999** [comment]
Thanks @rakarmp, yes I have already forked and included one for myself, just wondered whether it would be helpful for others. In any event this is a time saver for me. Thanks

**Comment by rakarmp** [comment]
> Thanks @rakarmp, yes I have already forked and included one for myself, just wondered whether it would be helpful for others. In any event this is a time saver for me. Thanks

no problem, hope it works well
